name: heidihoughting
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38866
title: heidi houghting artist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6968541576061398
  lightness: 0.4910693932324648
  saturation: 0.9737627177964896
  rhythmicContrast: 0.9356233288999647
purpose: []
